sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an Image With Docker File"
  - docker built -t ki0050/reacttest3 -f ./dockerfile.dev .

script:
  - docker run -e CI=true ki0050/reacttest3 npm run test -- --coverage

after_success:
  - echo "Test Success"